---
- name: Playbook to deprovision Amun

  hosts: localhost

  gather_facts: false
  connection: local

  tasks:
  - fail: msg="Bailing out. this play requires 'AMUN_API_NAMESPACE'"
    when: AMUN_API_NAMESPACE is not defined

  - fail: msg="Bailing out. this play requires 'AMUN_INSPECTION_NAMESPACE'"
    when: AMUN_INSPECTION_NAMESPACE is not defined

  - fail: msg="Bailing out. this play requires 'AMUN_INFRA_NAMESPACE'"
    when: AMUN_INFRA_NAMESPACE is not defined

  - name: "make sure to use project {{ AMUN_API_NAMESPACE }}"
    command: "oc project {{ AMUN_API_NAMESPACE }}"
    register: project_exists
    ignore_errors: true
    changed_when: False

  - name: Deprovision Amun API
    command: "oc delete bc,configmap,cronjob,dc,is,pod,role,rolebinding,route,\
      secret,svc,sa,template,clusterrole --selector 'app=amun'"

  - name: "make sure to use project {{ AMUN_INSPECTION_NAMESPACE }}"
    command: "oc project {{ AMUN_INSPECTION_NAMESPACE }}"
    register: project_exists
    ignore_errors: true
    changed_when: False

  - name: Deprovision Amun Inspection Namespace
    command: "oc delete bc,configmap,cronjob,dc,is,pod,role,rolebinding,route,\
      secret,svc,sa,template,clusterrole --selector 'app=amun'"

  - name: "make sure to use project {{ AMUN_INFRA_NAMESPACE }}"
    command: "oc project {{ AMUN_INFRA_NAMESPACE }}"
    register: project_exists
    ignore_errors: true
    changed_when: False

  - name: Deprovision Amun Infra Namespace
    command: "oc delete bc,configmap,cronjob,dc,is,pod,role,rolebinding,route,\
      secret,svc,sa,template,clusterrole --selector 'app=amun'"

